name: Build

on:
  push:
    branches: [master]
    tags:
      - '*'
  pull_request:
    branches: [master]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -A x64
        cmake --build ${{github.workspace}}/build --config Release
    - name: Upload windows build
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: ${{github.workspace}}/build/Analyzers/Release/*.dll
  
